name: Build on PR and push to master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: ./test.sh
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()  # run this step even if the previous step failed
        with:
          name: tests
          path: test/environment/test-report.xml
          reporter: jest-junit
